<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>promise</title>
</head>
<body>
    <script>
        // Promise 是异步编程的一种解决方案
        // 所谓Promise，简单说就是一个容器，里面保存着某个未来才会结束的事件（通常是一个异步操作）的结果
        // 从语法上说，Promise 是一个对象，从它可以获取异步操作的消息
        // (1) 对象的状态不受外界影响
        // 有三种状态：Pending（进行中）、Resolved（已完成，又称 Fulfilled）和Rejected（已失败）
        // 只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态
        // (2) 一旦状态改变，就不会再变，任何时候都可以得到这个结果
        // Promise对象的状态改变，只有两种可能：从Pending变为Resolved和从Pending变为Rejected
        // Promise也有一些缺点
        // 1. 无法取消Promise，一旦新建它就会立即执行，无法中途取消
        // 2. 如果不设置回调函数，Promise内部抛出的错误，不会反应到外部
        // 3. 当处于Pending状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）


        // ES6规定，Promise对象是一个构造函数，用来生成Promise实例
        // Promise构造函数接受一个函数作为参数
        // 该函数的两个参数分别是resolve和reject
        // 它们是两个函数，由JavaScript引擎提供，不用自己部署
        /*var promise = new Promise(function(resolve, reject) {
            // ... some code

            if (/!* 异步操作成功 *!/){
                resolve(value);
            } else {
                reject(error);
            }
        });*/
        // resolve函数的作用是，将Promise对象的状态从“未完成”变为“成功”（即从Pending变为Resolved）
        // 在异步操作成功时调用，并将异步操作的结果，作为参数传递出去
        // reject函数的作用是，将Promise对象的状态从“未完成”变为“失败”（即从Pending变为Rejected）
        // 在异步操作失败时调用，并将异步操作报出的错误，作为参数传递出去
        // Promise实例生成以后，可以用then方法分别指定Resolved状态和Reject状态的回调函数
        /*promise.then(function(value) {
            // success
        }, function(error) {
            // failure
        });*/
        // then方法可以接受两个回调函数作为参数
        // 第一个回调函数是Promise对象的状态变为Resolved时调用
        // 第二个回调函数是Promise对象的状态变为Reject时调用（可选）
        // 这两个函数都接受Promise对象传出的值作为参数
        function timeout(ms) {
            return new Promise((resolve, reject) => {
                setTimeout(resolve, ms, 'done');
            });
        }
        timeout(1000).then( value => console.log(value) );

        // Promise新建后就会立即执行
        let promise = new Promise(function(resolve, reject) {
            console.log('Promise');
            resolve();
        });

        promise.then(function() {
            console.log('Resolved.');
        });

        console.log('Hi!');

        // 异步加载图片的例子
        function loadImageAsync(url) {
            return new Promise(function(resolve, reject) {
                var image = new Image();

                image.onload = function() {
                    resolve(image);
                };

                image.onerror = function() {
                    reject(new Error('Could not load image at ' + url));
                };

                image.src = url;
            });
        }

        // then方法返回的是一个新的Promise实例（注意，不是原来那个Promise实例）
        // 因此可以采用链式写法，即then方法后面再调用另一个then方法


        // Promise.prototype.catch方法是.then(null, rejection)的别名，用于指定发生错误时的回调函数
        // 如果异步操作抛出错误，状态就会变为Rejected，就会调用catch方法指定的回调函数，处理这个错误
        // 另外，then方法指定的回调函数，如果运行中抛出错误，也会被catch方法捕获
        getJSON('/posts.json').then(function(posts) {
            // ...
        }).catch(function(error) {
            // 处理 getJSON 和 前一个回调函数运行时发生的错误
            console.log('发生错误！', error);
        });
        // 如果Promise状态已经变成Resolved，再抛出错误是无效的
        // Promise 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止
        // 也就是说，错误总是会被下一个catch语句捕获
        getJSON('/post/1.json').then(function(post) {
            return getJSON(post.commentURL);
        }).then(function(comments) {
            // some code
        }).catch(function(error) {
            // 处理前面三个Promise产生的错误
        });
        // 一共有三个Promise对象：一个由getJSON产生，两个由then产生
        // 它们之中任何一个抛出的错误，都会被最后一个catch捕获


        // 一般来说，不要在then方法里面定义Reject状态的回调函数（即then的第二个参数），总是使用catch方法
        // 如果没有使用catch方法指定错误处理的回调函数
        // Promise对象抛出的错误不会传递到外层代码，即不会有任何反应


        // catch方法返回的还是一个 Promise 对象，因此后面还可以接着调用then方法
        var someAsyncThing = function() {
            return new Promise(function(resolve, reject) {
                // 下面一行会报错，因为x没有声明
                resolve(x + 2);
            });
        };

        someAsyncThing()
            .catch(function(error) {
                console.log('oh no', error);
            })
            .then(function() {
                console.log('carry on');
            });


        // Promise.all方法用于将多个Promise实例，包装成一个新的Promise实例
        // Promise.all方法的参数可以不是数组，但必须具有Iterator接口，且返回的每个成员都是Promise实例
        // 如果不是，就会先调用Promise.resolve方法，将参数转为Promise实例，再进一步处理
        // var p = Promise.all([p1, p2, p3]);
        // p的状态由p1、p2、p3决定，分成两种情况
        // 1. 只有p1、p2、p3的状态都变成fulfilled，p的状态才会变成fulfilled
        // 此时p1、p2、p3的返回值组成一个数组，传递给p的回调函数
        // 2. 只要p1、p2、p3之中有一个被rejected，p的状态就变成rejected
        // 此时第一个被reject的实例的返回值，会传递给p的回调函数
        /*var promises = [2, 3, 5, 7, 11, 13].map(function (id) {
            return getJSON("/post/" + id + ".json");
        });

        Promise.all(promises).then(function (posts) {
            // ...
        }).catch(function(reason){
            // ...
        });*/


        // Promise.race方法同样是将多个Promise实例，包装成一个新的Promise实例
        // var p = Promise.race([p1, p2, p3]);
        // 只要p1、p2、p3之中有一个实例率先改变状态，p的状态就跟着改变
        // 那个率先改变的 Promise 实例的返回值，就传递给p的回调函数


        // Promise.resolve 将现有对象转为Promise对象
        /*Promise.resolve('foo')  ==> new Promise(resolve => resolve('foo'))*/
        // 1. 如果参数是Promise实例，那么Promise.resolve将不做任何修改、原封不动地返回这个实例
        // 2. 如果参数是一个thenable对象（thenable对象指的是具有then方法的对象）
        /*let thenable = {
            then: function(resolve, reject) {
                resolve(42);
            }
        };*/
        // Promise.resolve方法会将这个对象转为Promise对象，然后就立即执行thenable对象的then方法
        // 3. 参数不是具有then方法的对象，或根本就不是对象
        // Promise.resolve方法返回一个新的Promise对象，状态为Resolved
        // 4. Promise.resolve方法允许调用时不带参数，直接返回一个Resolved状态的Promise对象
        // 立即resolve的Promise对象，是在本轮“事件循环”（event loop）的结束时
        // 而不是在下一轮“事件循环”的开始时


        // Promise.reject(reason)方法也会返回一个新的 Promise 实例，该实例的状态为rejected
        // var p = Promise.reject('出错了'); ==> var p = new Promise((resolve, reject) => reject('出错了'))
        // Promise.reject()方法的参数，会原封不动地作为reject的理由，变成后续方法的参数


        // 不在ES6之中，但很有用的方法
        // Promise对象的回调链，不管以then方法或catch方法结尾，要是最后一个方法抛出错误
        // 都有可能无法捕捉到（因为Promise内部的错误不会冒泡到全局）
        // 可以提供一个done方法，总是处于回调链的尾端，保证抛出任何可能出现的错误
        /*asyncFunc()
            .then(f1)
            .catch(r1)
            .then(f2)
            .done();*/
        // 代码实现
        Promise.prototype.done = function (onFulfilled, onRejected) {
            this.then(onFulfilled, onRejected)
                .catch(function (reason) {
                    // 抛出一个全局错误
                    setTimeout(() => { throw reason }, 0);
                });
        };


        // finally方法用于指定不管Promise对象最后状态如何，都会执行的操作
        /*server.listen(0)
            .then(function () {
                // run test
            })
            .finally(server.stop);*/
        // 代码实现
        Promise.prototype.finally = function (callback) {
            let P = this.constructor;
            return this.then(
                value  => P.resolve(callback()).then(() => value),
                reason => P.resolve(callback()).then(() => { throw reason })
            );
        };


        // 不知道或者不想区分，函数f是同步函数还是异步操作但是想用 Promise 来处理它
        // 因为这样就可以不管f是否包含异步操作，都用then方法指定下一步流程
        // 用catch方法处理f抛出的错误
        // 一般写法:
        Promise.resolve().then(f);
        // 缺点： 如果f是同步函数，那么它会在本轮事件循环的末尾执行
        // 让同步函数同步执行，异步函数异步执行，并且让它们具有统一的 API
        // 1. 用async函数来写
        /*const f = () => console.log('now');
        (async () => f())();
        console.log('next');*/
        // 第二行是一个立即执行的匿名函数，会立即执行里面的async函数，因此如果f是同步的，就会得到同步的结果；
        // 如果f是异步的，就可以用then指定下一步
        /*(async () => f())()
            .then(...)*/
        // async () => f()会吃掉f()抛出的错误。所以，如果想捕获错误，要使用promise.catch方法
        /*(async () => f())()
            .then(...)
            .catch(...)*/
        // 2. 使用new Promise()
        /*const f = () => console.log('now');
        (
            () => new Promise(
                resolve => resolve(f())
            )
        )();
        console.log('next');
        // now
        // next*/
        // 使用 promise.try 目前还在提案阶段，promise 库对此都有实现
    </script>
</body>
</html>